module.exports.nsfw = [
  {
    randomHentaiGif: "/img/Random_hentai_gif",
    pussy: "/img/pussy",
    nekoGif: "/img/nsfw_neko_gif",
    neko: "/img/lewd",
    lesbian: "/img/les",
    kuni: "/img/kuni",
    cumsluts: "/img/cum",
    classic: "/img/classic",
    boobs: "/img/boobs",
    bJ: "/img/bj",
    anal: "/img/anal",
    avatar: "/img/nsfw_avatar",
    yuri: "/img/yuri",
    trap: "/img/trap",
    tits: "/img/tits",
    girlSoloGif: "/img/solog",
    girlSolo: "/img/solo",
    pussyWankGif: "/img/pwankg",
    pussyArt: "/img/pussy_jpg",
    kemonomimi: "/img/lewdkemo",
    kitsune: "/img/lewdk",
    keta: "/img/keta",
    holo: "/img/hololewd",
    holoEro: "/img/holoero",
    hentai: "/img/hentai",
    futanari: "/img/futanari",
    femdom: "/img/femdom",
    feetGif: "/img/feetg",
    eroFeet: "/img/erofeet",
    feet: "/img/feet",
    ero: "/img/ero",
    eroKitsune: "/img/erok",
    eroKemonomimi: "/img/erokemo",
    eroNeko: "/img/eron",
    eroYuri: "/img/eroyuri",
    cumArts: "/img/cum_jpg",
    blowJob: "/img/blowjob",
    spank: "/img/spank",
    gasm: "/img/gasm"
  }
]
module.exports.sfw = [
  {
    tickle: "/img/tickle",
    slap: "/img/slap",
    poke: "/img/poke",
    pat: "/img/pat",
    neko: "/img/neko",
    meow: "/img/meow",
    lizard: "/img/lizard",
    kiss: "/img/kiss",
    hug: "/img/hug",
    foxGirl: "/img/fox_girl",
    feed: "/img/feed",
    cuddle: "/img/cuddle",
    why: "/why",
    catText: "/cat",
    OwOify: "/owoify",
    Ball8: "/8ball",
    fact: "/fact",
    nekoGif: "/img/ngif",
    kemonomimi: "/img/kemonomimi",
    holo: "/img/holo",
    smug: "/img/smug",
    baka: "/img/baka",
    woof: "/img/woof",
    spoiler: "/spoiler",
    wallpaper: "/img/wallpaper",
    goose: "/img/goose",
    gecg: "/img/gecg",
    avatar: "/img/avatar",
    waifu: "/img/waifu"
  }
]
module.exports.nsfwAZ = `anal avatar bJ blowJob boobs classic cumArts cumsluts ero eroFeet eroKemonomimi eroKitsune eroNeko eroYuri feet feetGif femdom futanari gasm girlSolo girlSoloGif hentai holo holoEro kemonomimi keta kitsune kuni lesbian neko nekoGif pussy pussyArt pussyWankGif randomHentaiGif spank tits trap yuri`

module.exports.sfwAZ = `avatar baka Ball8 catText cuddle fact feed foxGirl gecg goose holo hug kemonomimi kiss lizard meow neko nekoGif OwOify pat poke slap smug spoiler tickle waifu wallpaper why woof`